use anyhow::Result;
use std::fs;

use crate::core::types::{ScanResult, Severity};

pub fn write(result: &ScanResult, format: &str, path: Option<&str>) -> Result<()> {
    match format {
        "json" => {
            let out = to_json(result)?;
            write_output(&out, path)?;
        }
        "markdown" | "md" => {
            let out = to_markdown(result);
            write_output(&out, path)?;
        }
        "both" => {
            let json_path = path.map(|p| format!("{}.json", p));
            let md_path = path.map(|p| format!("{}.md", p));
            write_output(&to_json(result)?, json_path.as_deref())?;
            write_output(&to_markdown(result), md_path.as_deref())?;
        }
        _ => {
            let out = to_json(result)?;
            write_output(&out, path)?;
        }
    }
    Ok(())
}

fn write_output(content: &str, path: Option<&str>) -> Result<()> {
    match path {
        Some(p) => {
            fs::write(p, content)?;
            println!("\n  Saved → {}", p);
        }
        None => println!("\n{}", content),
    }
    Ok(())
}

fn to_json(result: &ScanResult) -> Result<String> {
    Ok(serde_json::to_string_pretty(result)?)
}

fn to_markdown(result: &ScanResult) -> String {
    let mut md = String::new();

    md.push_str("# openxos-ghost — Scan Report\n\n");
    md.push_str(&format!("**Target:** `{}`  \n", result.target));
    md.push_str(&format!("**Mode:** {:?}  \n", result.mode));
    md.push_str(&format!("**Profile:** `{}`  \n", result.profile));
    md.push_str(&format!(
        "**Started:** {}  \n",
        result.started_at.format("%Y-%m-%d %H:%M:%S UTC")
    ));
    md.push_str(&format!(
        "**Completed:** {}  \n\n",
        result.completed_at.format("%Y-%m-%d %H:%M:%S UTC")
    ));

    // Evasion summary
    md.push_str("## Evasion Summary\n\n");
    if let Some(waf) = &result.evasion_summary.waf_detected {
        md.push_str(&format!("**WAF Detected:** {}  \n\n", waf));
    } else {
        md.push_str("**WAF Detected:** None  \n\n");
    }

    md.push_str("**Techniques Attempted:**\n");
    for t in &result.evasion_summary.techniques_attempted {
        md.push_str(&format!("- {}\n", t));
    }

    md.push_str("\n**Techniques That Succeeded:**\n");
    if result.evasion_summary.techniques_succeeded.is_empty() {
        md.push_str("- None\n");
    } else {
        for t in &result.evasion_summary.techniques_succeeded {
            md.push_str(&format!("- {}\n", t));
        }
    }

    md.push_str("\n**Detection Gaps Identified:**\n");
    if result.evasion_summary.detection_gaps.is_empty() {
        md.push_str("- None identified\n");
    } else {
        for g in &result.evasion_summary.detection_gaps {
            md.push_str(&format!("- {}\n", g));
        }
    }

    // Findings
    md.push_str(&format!(
        "\n## Findings ({} total)\n\n",
        result.findings.len()
    ));

    if result.findings.is_empty() {
        md.push_str("No findings recorded.\n");
    } else {
        for (i, f) in result.findings.iter().enumerate() {
            md.push_str(&format!(
                "### {} [{}] {}\n\n",
                i + 1,
                severity_label(&f.severity),
                f.title
            ));
            md.push_str(&format!("**Description:** {}  \n\n", f.description));
            md.push_str(&format!(
                "**Evasion Technique:** {}  \n",
                f.evasion_technique
            ));
            md.push_str(&format!("**Detection Gap:** {}  \n\n", f.detection_gap));
            md.push_str("**Evidence:**\n");
            md.push_str(&format!("```\n{}\n```\n\n", f.evidence.request));
            if let Some(code) = f.evidence.response_code {
                md.push_str(&format!("Response: HTTP {}  \n\n", code));
            }
            if let Some(curl) = &f.evidence.curl_repro {
                md.push_str("**Reproduce:**\n");
                md.push_str(&format!("```bash\n{}\n```\n\n", curl));
            }
            md.push_str("---\n\n");
        }
    }

    md.push_str(
        "*Generated by [openxos-ghost](https://github.com/Openxosdev) — authorized testing only*\n",
    );
    md
}

fn severity_label(s: &Severity) -> &'static str {
    match s {
        Severity::Critical => "CRITICAL",
        Severity::High => "HIGH",
        Severity::Medium => "MEDIUM",
        Severity::Low => "LOW",
        Severity::Info => "INFO",
    }
}

#[cfg(test)]
mod tests {
    use super::write;
    use crate::core::types::{EvasionSummary, Evidence, Finding, ScanMode, ScanResult, Severity};
    use chrono::Utc;
    use std::fs;
    use std::path::PathBuf;

    fn sample_result() -> ScanResult {
        ScanResult {
            mode: ScanMode::Web,
            target: "https://example.com".into(),
            profile: "slow".into(),
            started_at: Utc::now(),
            completed_at: Utc::now(),
            findings: vec![Finding {
                severity: Severity::Low,
                title: "Sample finding".into(),
                description: "Sample description".into(),
                evasion_technique: "Sample technique".into(),
                detection_gap: "Sample gap".into(),
                evidence: Evidence {
                    request: "GET / HTTP/1.1".into(),
                    response_code: Some(200),
                    response_snippet: None,
                    curl_repro: Some("curl https://example.com".into()),
                },
            }],
            evasion_summary: EvasionSummary {
                waf_detected: Some("Cloudflare".into()),
                techniques_attempted: vec!["A".into(), "B".into()],
                techniques_succeeded: vec!["A".into()],
                detection_gaps: vec!["Gap".into()],
            },
        }
    }

    fn unique_temp_path(stem: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system time should be after unix epoch")
            .as_nanos();
        p.push(format!("openxos-ghost-{}-{}", stem, nanos));
        p
    }

    #[test]
    fn write_json_output_file() {
        let out = unique_temp_path("json");
        let out_str = out.to_string_lossy().to_string();

        write(&sample_result(), "json", Some(&out_str)).expect("json write should succeed");
        let content = fs::read_to_string(&out).expect("json output file should exist");
        assert!(content.contains("\"target\": \"https://example.com\""));

        let _ = fs::remove_file(out);
    }

    #[test]
    fn write_markdown_output_file() {
        let out = unique_temp_path("md");
        let out_str = out.to_string_lossy().to_string();

        write(&sample_result(), "markdown", Some(&out_str)).expect("markdown write should succeed");
        let content = fs::read_to_string(&out).expect("markdown output file should exist");
        assert!(content.contains("# openxos-ghost"));
        assert!(content.contains("## Findings"));

        let _ = fs::remove_file(out);
    }

    #[test]
    fn write_both_creates_two_files() {
        let out_base = unique_temp_path("both");
        let out_base_str = out_base.to_string_lossy().to_string();
        let json_out = format!("{}.json", out_base_str);
        let md_out = format!("{}.md", out_base_str);

        write(&sample_result(), "both", Some(&out_base_str)).expect("both write should succeed");

        let json_content = fs::read_to_string(&json_out).expect("both should create json file");
        let md_content = fs::read_to_string(&md_out).expect("both should create markdown file");
        assert!(json_content.contains("\"findings\""));
        assert!(md_content.contains("## Evasion Summary"));

        let _ = fs::remove_file(json_out);
        let _ = fs::remove_file(md_out);
    }
}
